load("//build_defs:defs.bzl", "lute_cxx_library")
load("@prelude//utils/glob_defs.bzl", "subdir_glob")

lute_cxx_library(
    name = "Lute.Definitions",
    srcs = [
        "src/lutemodules.cpp",
        "src/generated/modules.cpp",
    ],
    exported_headers = subdir_glob([("include", "**/*.h")]),
    headers = {
        "generated/modules.h": "src/generated/modules.h",
        "modules.h": "src/generated/modules.h",
    },
)
