name: "Setup and Build"
description: "Install dependencies, configure and build target"

inputs:
  target:
    description: "Which target to build"
    required: true
  config:
    description: "Build configuration (debug or release)"
    required: false
    default: "debug"
  options:
    description: "Additional luthier options"
    required: false
    default: ""
  token:
    description: "Token for foreman"
    required: true

outputs:
  exe_path:
    description: "Path to the compiled executable"
    value: ${{ steps.artifact_path.outputs.exe_path }}

runs:
  using: "composite"
  steps:
    - name: Install tools
      uses: Roblox/setup-foreman@v3
      with:
        token: ${{ inputs.token }}
        allow-external-github-orgs: true

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build clang

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew update
        brew unlink brotli zstd

    - name: Set up MSVC
      if: runner.os == 'Windows'
      uses: luau-lang/msvc-dev-cmd@v1

    - name: Set up NASM
      if: runner.os == 'Windows'
      uses: luau-lang/setup-nasm@v1

    - name: Cache extern folder
      uses: actions/cache@v4
      id: cache-extern
      with:
        path: extern
        key: extern-${{ hashFiles('extern/*.tune') }}

    # We can currently only bootstrap correctly in ci on mac/linux
    - name: Bootstrap Lute (Darwin/Linux only)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        ./tools/bootstrap.sh
        correct_lute=$(./build/bootstrapped-lute tools/luthier.luau build lute --config debug --which)
        mv $correct_lute ./build/lute
        echo "luthier_lute=./build/lute" >> $GITHUB_ENV

    - name: Build ${{ inputs.target }} ${{ runner.os }}
      if: runner.os != 'Windows'
      shell: bash
      run: $luthier_lute ./tools/luthier.luau build ${{ inputs.target }} --config ${{ inputs.config}} ${{ inputs.options }}

    - name: Fetch ${{ inputs.target }}
      if: steps.cache-extern.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: bash
      run: lute ./tools/luthier.luau fetch ${{ inputs.target }}

    - name: Configure ${{ inputs.target }}
      if: runner.os == 'Windows'
      shell: bash
      run: lute ./tools/luthier.luau configure ${{ inputs.target }} --config ${{ inputs.config }} ${{ inputs.options }}

    - name: Build ${{ inputs.target }}
      if: runner.os == 'Windows'
      shell: bash
      run: lute ./tools/luthier.luau build ${{ inputs.target }} --config ${{ inputs.config }} ${{ inputs.options }}

    - name: Get Artifact Path
      id: artifact_path
      shell: bash
      run: |
        if [[ ${{ runner.os }} == "Windows" ]]; then
          LUTE="lute"
        else
          LUTE="$luthier_lute"
        fi
        exe_path=$($LUTE ./tools/luthier.luau build ${{ inputs.target }} --config ${{ inputs.config }} --which)
        echo "Executable path: $exe_path"  # Debug print
        echo "exe_path=$exe_path" >> "$GITHUB_OUTPUT"
