load("//build_defs:defs.bzl", "lute_cxx_library")
load("@prelude//utils/glob_defs.bzl", "subdir_glob")

lute_cxx_library(
    name = "Lute.IO",
    srcs = [
        "src/io.cpp",
    ],
    exported_headers = subdir_glob([("include", "**/*.h")]),
    deps = [
        "//lute/runtime:Lute.Runtime",
        "//extern:Luau.VM",
        "//extern:libuv",
    ],
)
