#include "lute/clicommands.h"

// This file provides luteclicommands and is auto-generated by luthier.luau.
// If it is not present or outdated, re-configure using luthier.luau.
#include "commands.h"

#include <array>
#include <optional>
#include <string>
#include <string_view>
#include <utility>

CliModuleResult getCliModule(std::string_view path)
{
    for (const EmbeddedModule& module : luteclicommands)
    {
        if (path != module.path)
            continue;

        if (module.isDirectory)
            return {CliModuleType::Directory};

        std::optional<std::string> contents = decompressEmbeddedModule(module);
        if (contents)
            return {CliModuleType::Module, std::move(*contents)};
    }

    return {CliModuleType::NotFound};
}

std::optional<CliCommandResult> getCliCommand(std::string_view command)
{
    const std::array<std::string, 2> pathOptions = {"@cli/" + std::string(command) + ".luau", "@cli/" + std::string(command) + "/init.luau"};

    for (const std::string& path : pathOptions)
    {
        CliModuleResult result = getCliModule(path);
        if (result.type == CliModuleType::Module)
        {
            return CliCommandResult{std::move(result.contents), path};
        }
    }

    return std::nullopt;
}
