load("//build_defs:defs.bzl", "lute_cxx_library")
load("@prelude//utils/glob_defs.bzl", "subdir_glob")

lute_cxx_library(
    name = "Lute.Common",
    srcs = [
        "src/fileutils.cpp",
    ],
    exported_headers = subdir_glob([("include", "**/*.h")]),
    deps = [
        "//extern:Luau.CLI.lib",
        "//extern:Luau.Common",
    ],
)
