#include "clicommands.h"

// This file provides luteclicommands and is auto-generated by luthier.luau.
// If it is not present or outdated, re-configure using luthier.luau.
#include "generated/commands.h"

#include <string_view>
#include <utility>

CliModuleResult getCliModule(std::string_view path)
{
    for (const auto& [pathInLib, contents] : luteclicommands)
    {
        if (path != pathInLib)
            continue;

        if (contents == "#directory")
            return {CliModuleType::Directory};
        else
            return {CliModuleType::Module, contents};
    }

    return {CliModuleType::NotFound};
}
