load("//build_defs:defs.bzl", "lute_cxx_library")
load("@prelude//utils/glob_defs.bzl", "subdir_glob")

lute_cxx_library(
    name = "Lute.Batteries",
    srcs = [
        "src/clibatteries.cpp",
        "generated/batteries.cpp",
    ],
    exported_headers = subdir_glob([("include", "**/*.h")]),
    headers = {
        "batteries.h": "generated/batteries.h",
    },
    deps = [
        "//extern:libuv",
    ],
)
