import { defineConfig } from 'vitepress'
import { withSidebar } from 'vitepress-sidebar'

export default withSidebar(
  defineConfig({
    title: 'Lute',
    description: 'Luau for General-Purpose Programming',
    base: "/",
    redirects: {
      '/reference/': '/std/',
      '/reference/index': '/std/',
      // lute runtime redirects
      '/reference/lute/': '/lute/',
      '/reference/lute/index': '/lute/',
      '/reference/lute/crypto': '/lute/crypto',
      '/reference/lute/fs': '/lute/fs',
      '/reference/lute/io': '/lute/io',
      '/reference/lute/luau': '/lute/luau',
      '/reference/lute/net': '/lute/net/',
      '/reference/lute/net/': '/lute/net/',
      '/reference/lute/net/index': '/lute/net/',
      '/reference/lute/net/client': '/lute/net/client',
      '/reference/lute/net/server': '/lute/net/server',
      '/reference/lute/process': '/lute/process',
      '/reference/lute/system': '/lute/system',
      '/reference/lute/task': '/lute/task',
      '/reference/lute/time': '/lute/time',
      '/reference/lute/vm': '/lute/vm',
      // std library redirects
      '/reference/std/': '/std/',
      '/reference/std/index': '/std/',
      '/reference/std/fs': '/std/fs',
      '/reference/std/io': '/std/io',
      '/reference/std/json': '/std/json',
      '/reference/std/luau': '/std/luau',
      '/reference/std/net': '/std/net',
      '/reference/std/path/': '/std/path/',
      '/reference/std/path/index': '/std/path/',
      '/reference/std/path/pathinterface': '/std/path/pathinterface',
      '/reference/std/path/posix/': '/std/path/posix/',
      '/reference/std/path/posix/index': '/std/path/posix/',
      '/reference/std/path/posix/types': '/std/path/posix/types',
      '/reference/std/path/types': '/std/path/types',
      '/reference/std/path/win32/': '/std/path/win32/',
      '/reference/std/path/win32/index': '/std/path/win32/',
      '/reference/std/path/win32/types': '/std/path/win32/types',
      '/reference/std/process': '/std/process',
      '/reference/std/stringext': '/std/stringext',
      '/reference/std/syntax/': '/std/syntax/',
      '/reference/std/syntax/index': '/std/syntax/',
      '/reference/std/syntax/parser': '/std/syntax/parser',
      '/reference/std/syntax/printer': '/std/syntax/printer',
      '/reference/std/syntax/query': '/std/syntax/query',
      '/reference/std/syntax/types': '/std/syntax/types',
      '/reference/std/syntax/utils/': '/std/syntax/utils/',
      '/reference/std/syntax/utils/index': '/std/syntax/utils/',
      '/reference/std/syntax/utils/trivia': '/std/syntax/utils/trivia',
      '/reference/std/syntax/visitor': '/std/syntax/visitor',
      '/reference/std/system/': '/std/system/',
      '/reference/std/system/index': '/std/system/',
      '/reference/std/system/platform': '/std/system/platform',
      '/reference/std/tableext': '/std/tableext',
      '/reference/std/task': '/std/task',
      '/reference/std/test/': '/std/test/',
      '/reference/std/test/index': '/std/test/',
      '/reference/std/test/assert': '/std/test/assert',
      '/reference/std/test/env': '/std/test/env',
      '/reference/std/test/failure': '/std/test/failure',
      '/reference/std/test/reporter': '/std/test/reporter',
      '/reference/std/test/runner': '/std/test/runner',
      '/reference/std/test/types': '/std/test/types',
      '/reference/std/time/': '/std/time/',
      '/reference/std/time/index': '/std/time/',
      '/reference/std/time/duration': '/std/time/duration',
    },
    themeConfig: {
      nav: [
        { text: 'Guide', link: '/guide/installation' },
        { text: 'CLI', link: '/cli/' },
        { text: 'Standard Library', link: '/std' },
      ],
      search: { provider: 'local' },
      socialLinks: [
        { icon: 'github', link: 'https://github.com/luau-lang/lute' },
      ],
    },
  }),
  {
    // ============ [ SIDEBAR OPTIONS ] ============
    useFolderLinkFromIndexFile: true,
    useFolderTitleFromIndexFile: true,
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    hyphenToSpace: true,
    sortMenusByFrontmatterOrder: true,
    frontmatterOrderDefaultValue: 100,
    excludeByGlobPattern: ['README.md'],
  }
)
