load("//build_defs:defs.bzl", "lute_cxx_library")
load("@prelude//utils/glob_defs.bzl", "subdir_glob")

lute_cxx_library(
    name = "Lute.Syntax",
    srcs = [
        "src/parser.cpp",
        "src/syntax.cpp",
    ],
    exported_headers = subdir_glob([("include", "**/*.h")]),
    deps = [
        "//lute/common:Lute.Common",
        "//lute/runtime:Lute.Runtime",
        "//extern:Luau.Analysis",
        "//extern:Luau.Ast",
        "//extern:Luau.VM",
    ],
)
