#include "lute/lutemodules.h"

// This file provides lutedefinitions and is auto-generated by luthier.luau.
// If it is not present or outdated, re-configure using luthier.luau.
#include "generated/modules.h"

#include <optional>
#include <string>
#include <string_view>
#include <utility>

LuteModuleResult getLuteModule(std::string_view path)
{
    for (const EmbeddedModule& module : lutedefinitions)
    {
        if (path != module.path)
            continue;

        if (module.isDirectory)
            return {LuteModuleType::Directory};

        std::optional<std::string> contents = decompressEmbeddedModule(module);
        if (contents)
            return {LuteModuleType::Module, std::move(*contents)};
    }

    return {LuteModuleType::NotFound};
}
