#include "lute/lutemodules.h"

// This file provides lutedefinitions and is auto-generated by luthier.luau.
// If it is not present or outdated, re-configure using luthier.luau.
#include "generated/modules.h"

#include <string_view>
#include <utility>

LuteModuleResult getLuteModule(std::string_view path)
{
    for (const auto& [pathInLib, contents] : lutedefinitions)
    {
        if (path != pathInLib)
            continue;

        if (contents == "#directory")
            return {LuteModuleType::Directory};
        else
            return {LuteModuleType::Module, contents};
    }

    return {LuteModuleType::NotFound};
}
