// This file is auto-generated by luthier.luau. Do not edit.
// Instead, you should modify the source files in `batteries`.

#include "batteries.h"

constexpr std::pair<std::string_view, std::string_view> lutebatteries[] = {{"", ""}};
