// This file is auto-generated by luthier.luau. Do not edit.
// Instead, you should modify the source files in `batteries`.

#include "batteries.h"

const EmbeddedModule lutebatteries[] = {{"", std::string_view{}, 0, true}};
