// This file is auto-generated by the bootstrap script. Do not edit.
// The real bundle is produced by luthier.luau from
// `extern/nss/lib/ckfw/builtins/certdata.txt` via curl's `mk-ca-bundle.pl`.
#include "cacerts.h"

const std::pair<std::string_view, std::string_view> lutecacerts[] = {{"", ""}};
