// This file is auto-generated by the bootstrap script. Do not edit.
// The real bundle is produced by luthier.luau from
// `extern/nss/lib/ckfw/builtins/certdata.txt` via curl's `mk-ca-bundle.pl`.
#pragma once

#include <string_view>
#include <utility>

extern const std::pair<std::string_view, std::string_view> lutecacerts[1];
