// This file is auto-generated by the bootstrap script. Do not edit.
// Instead, you should modify the source files in `std/libs`.
#pragma once

#include "lute/embeddedmodule.h"

extern const EmbeddedModule luteclicommands[1];

