// This file is auto-generated by the bootstrap script. Do not edit.
// Instead, you should modify the source files in `std/libs`.

#include "commands.h"

const EmbeddedModule luteclicommands[] = {{"", std::string_view{}, 0, true}};

