// This file is auto-generated by the bootstrap script. Do not edit.
// Instead, you should modify the source files in `std/libs`.
#pragma once

#include <string_view>
#include <utility>

extern const std::pair<std::string_view, std::string_view> luteclicommands[1];

