// This file is auto-generated by the bootstrap script. Do not edit.
// Instead, you should modify the source files in `definitions`.

#include "modules.h"

const EmbeddedModule lutedefinitions[] = {{"", std::string_view{}, 0, true}};
