// This file is auto-generated by the bootstrap script. Do not edit.
// Instead, you should modify the source files in `definitions`.
#pragma once

#include "lute/embeddedmodule.h"

extern const EmbeddedModule lutedefinitions[1];
