// This file is auto-generated by the bootstrap script. Do not edit.
// Instead, you should modify the source files in `std/libs`.

#include <utility>
#include "modules.h"

constexpr std::pair<std::string_view, std::string_view> lutestdlib[] = {{"", ""}};

