// This file is auto-generated by the bootstrap script. Do not edit.
// Instead, you should modify the source files in `std/libs`.

#include "modules.h"

const EmbeddedModule lutestdlib[] = {{"", std::string_view{}, 0, true}};

