cmake_minimum_required(VERSION 3.13)

set(LUTE_VERSION 0.1.0)

set(LUTE_VERSION_SUFFIX_DEFAULT "$ENV{LUTE_VERSION_SUFFIX}")
if(NOT DEFINED LUTE_VERSION_SUFFIX AND NOT "${LUTE_VERSION_SUFFIX_DEFAULT}" STREQUAL "")
    set(LUTE_VERSION_SUFFIX "${LUTE_VERSION_SUFFIX_DEFAULT}")
endif()
set(LUTE_VERSION_SUFFIX "${LUTE_VERSION_SUFFIX}" CACHE STRING "Optional suffix appended to the Lute version string")
set(LUTE_VERSION_FULL "${LUTE_VERSION}")
if(LUTE_VERSION_SUFFIX)
    set(LUTE_VERSION_FULL "${LUTE_VERSION_FULL}-${LUTE_VERSION_SUFFIX}")
endif()

message("${LUTE_VERSION_FULL}")
