#!/usr/bin/env python3
"""Embed Luau source files into C++ arrays for Buck2 genrule.

Replicates the code generation from luthier.luau: walks a directory tree,
reads .luau and .luaurc files, and produces a C++ header/source pair
containing an array of {path, content} pairs.
"""
import argparse
import os
import sys


def collect_files(source_dir):
    """Collect .luau and .luaurc files, sorted by relative path.

    init.luau files also get a directory-name alias entry (e.g., @std/path
    in addition to @std/path/init.luau).
    """
    entries = []
    for root, _dirs, files in os.walk(source_dir):
        for name in files:
            if name.endswith(".luau") or name == ".luaurc":
                full = os.path.join(root, name)
                rel = os.path.relpath(full, source_dir)
                entries.append((rel, full))
                if name == "init.luau":
                    dir_rel = os.path.dirname(rel)
                    if dir_rel:
                        entries.append((dir_rel, full))
    entries.sort(key=lambda x: x[0])
    return entries


def main():
    parser = argparse.ArgumentParser(description="Embed Luau sources into C++")
    parser.add_argument("--source-dir", required=True, help="Directory to walk")
    parser.add_argument("--alias", required=True, help="Module alias prefix (e.g. @std)")
    parser.add_argument("--array-name", required=True, help="C++ array variable name")
    parser.add_argument("--output-dir", required=True, help="Output directory for .h and .cpp")
    parser.add_argument("--header-name", default="modules.h", help="Output header filename")
    parser.add_argument("--source-name", default="modules.cpp", help="Output source filename")
    args = parser.parse_args()

    entries = collect_files(args.source_dir)
    if not entries:
        print(f"Warning: no .luau or .luaurc files found in {args.source_dir}", file=sys.stderr)

    os.makedirs(args.output_dir, exist_ok=True)

    header_path = os.path.join(args.output_dir, args.header_name)
    source_path = os.path.join(args.output_dir, args.source_name)

    with open(header_path, "w") as h:
        h.write("// This file is auto-generated by embed_sources.py. Do not edit.\n")
        h.write("#pragma once\n\n")
        h.write("#include <string_view>\n")
        h.write("#include <utility>\n\n")
        h.write(f"extern const std::pair<std::string_view, std::string_view> {args.array_name}[{len(entries)}];\n")

    with open(source_path, "w") as s:
        s.write("// This file is auto-generated by embed_sources.py. Do not edit.\n\n")
        s.write(f'#include "{args.header_name}"\n\n')
        s.write(f"const std::pair<std::string_view, std::string_view> {args.array_name}[] = {{\n\n")

        for rel_path, full_path in entries:
            module_path = f"{args.alias}/{rel_path}"
            with open(full_path, "r") as f:
                content = f.read()
            s.write(f'    {{"{module_path}", R"MODULES_MOD({content})MODULES_MOD"}},\n\n')

        s.write("};\n")

    print(f"Generated {len(entries)} entries -> {header_path}, {source_path}")


if __name__ == "__main__":
    main()
