#include "lute/stdlib.h"

// This file provides lutestdlib and is auto-generated by luthier.luau.
// If it is not present or outdated, re-configure using luthier.luau.
#include "generated/modules.h"

#include <optional>
#include <string>
#include <string_view>
#include <utility>

StdLibModuleResult getStdLibModule(std::string_view path)
{
    for (const EmbeddedModule& module : lutestdlib)
    {
        if (path != module.path)
            continue;

        if (module.isDirectory)
            return {StdLibModuleType::Directory};

        std::optional<std::string> contents = decompressEmbeddedModule(module);
        if (contents)
            return {StdLibModuleType::Module, std::move(*contents)};
    }

    return {StdLibModuleType::NotFound};
}
