#include "lute/stdlib.h"

// This file provides lutestdlib and is auto-generated by luthier.luau.
// If it is not present or outdated, re-configure using luthier.luau.
#include "lute_std_files.h"

#include <string_view>
#include <utility>

StdLibModuleResult getStdLibModule(std::string_view path)
{
    for (const auto& [pathInLib, contents] : LUTE_STD)
    {
        if (pathInLib.find(path) == 0 && path.substr(0, pathInLib.find_last_of("/")) == path)
            return {StdLibModuleType::Directory};

        if (path != pathInLib)
            continue;

        return {StdLibModuleType::Module, contents};
    }

    return {StdLibModuleType::NotFound};
}
