load("//build_defs:defs.bzl", "lute_cxx_library")
load("@prelude//rules.bzl", "cxx_library")
load("@prelude//utils/glob_defs.bzl", "subdir_glob")

# Header-only target to break the circular dependency with Lute.Require.
# Lute.Require needs lute/luau.h at compile time, and Lute.Luau needs
# Lute.Require's headers. We break the cycle by exposing only headers here.
cxx_library(
    name = "Lute.Luau.headers",
    exported_headers = subdir_glob([("include", "**/*.h")]),
    header_namespace = "",
    preferred_linkage = "static",
    default_target_platform = "//platforms:default",
    visibility = ["PUBLIC"],
)

lute_cxx_library(
    name = "Lute.Luau",
    srcs = [
        "src/configresolver.cpp",
        "src/luau.cpp",
        "src/tcmoduleresolver.cpp",
        "src/resolvemodule.cpp",
        "src/type.cpp",
    ],
    exported_headers = subdir_glob([("include", "**/*.h")]),
    deps = [
        "//lute/common:Lute.Common",
        "//lute/require:Lute.Require",
        "//lute/runtime:Lute.Runtime",
        "//lute/syntax:Lute.Syntax",
        "//extern:Luau.Analysis",
        "//extern:Luau.Ast",
        "//extern:Luau.Compiler",
        "//extern:Luau.CLI.lib",
        "//extern:Luau.Require",
        "//extern:Luau.VM",
        "//extern:libuv",
    ],
)
