name: build

on:
  push:
    branches: ["primary"]
  pull_request:
    branches: ["primary"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            build_type: debug
          - os: ubuntu-latest
            build_type: debug
            options: --c-compiler=gcc --cxx-compiler=g++
          - os: ubuntu-latest
            build_type: debug
            options: --c-compiler=clang --cxx-compiler=clang++
          - os: macos-latest
            build_type: debug
            options: --c-compiler=clang --cxx-compiler=clang++
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup and Build Lute
        uses: ./.github/actions/setup-and-build
        with:
          config: ${{ matrix.build_type }}
          options: ${{ matrix.options }}
